create table if not exists public.rsvp_responses (
    id integer generated by default as identity primary key,
    first_name text not null check (char_length(btrim(first_name)) between 1 and 100),
    last_name text not null check (char_length(btrim(last_name)) between 1 and 100),
    adults_count integer not null check (adults_count between 1 and 12),
    children_count integer not null check (children_count between 0 and 12),
    food_notes text null check (food_notes is null or char_length(food_notes) <= 1000),
    created_at_utc timestamptz not null default now(),
    constraint rsvp_responses_total_guests_check check (adults_count + children_count <= 12)
);

create index if not exists ix_rsvp_responses_created_at_utc
    on public.rsvp_responses (created_at_utc desc);

create table if not exists public.admin_users (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at_utc timestamptz not null default now()
);

alter table public.rsvp_responses enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public, auth
as $$
    select exists (
        select 1
        from public.admin_users
        where user_id = auth.uid()
    );
$$;

grant execute on function public.is_admin() to anon, authenticated;
grant select, insert, update, delete on public.rsvp_responses to anon, authenticated;
grant select on public.admin_users to authenticated;

drop policy if exists "Anyone can submit RSVP responses" on public.rsvp_responses;
create policy "Anyone can submit RSVP responses"
on public.rsvp_responses
for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read RSVP responses" on public.rsvp_responses;
create policy "Admins can read RSVP responses"
on public.rsvp_responses
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can update RSVP responses" on public.rsvp_responses;
create policy "Admins can update RSVP responses"
on public.rsvp_responses
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete RSVP responses" on public.rsvp_responses;
create policy "Admins can delete RSVP responses"
on public.rsvp_responses
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Admins can read admin users" on public.admin_users;
create policy "Admins can read admin users"
on public.admin_users
for select
to authenticated
using (public.is_admin());

-- After creating the admin user in Supabase Auth, run this with that user's id:
-- insert into public.admin_users (user_id) values ('00000000-0000-0000-0000-000000000000');