-- Redesign RSVP: replace flat adults/children counts with named, per-guest records.
-- Supersedes 001_create_rsvp_schema.sql's rsvp_responses table (no production data to migrate).

drop table if exists public.rsvp_responses;

create table if not exists public.rsvp_parties (
    id integer generated by default as identity primary key,
    notes text null check (notes is null or char_length(notes) <= 1000),
    created_at_utc timestamptz not null default now()
);

create index if not exists ix_rsvp_parties_created_at_utc
    on public.rsvp_parties (created_at_utc desc);

create table if not exists public.rsvp_guests (
    id integer generated by default as identity primary key,
    party_id integer not null references public.rsvp_parties(id) on delete cascade,
    first_name text not null check (char_length(btrim(first_name)) between 1 and 100),
    last_name text not null check (char_length(btrim(last_name)) between 1 and 100),
    is_child boolean not null default false,
    age smallint null check (age is null or age between 0 and 17),
    allergies text null check (allergies is null or char_length(allergies) <= 500),
    is_primary_contact boolean not null default false,
    guest_order smallint not null default 0,
    constraint rsvp_guests_age_matches_is_child check (
        (is_child and age is not null) or (not is_child and age is null)
    )
);

create index if not exists ix_rsvp_guests_party_id
    on public.rsvp_guests (party_id);

create unique index if not exists ix_rsvp_guests_one_primary_per_party
    on public.rsvp_guests (party_id)
    where is_primary_contact;

create or replace function public.enforce_rsvp_party_guest_limit()
returns trigger
language plpgsql
as $$
begin
    if (
        select count(*) from public.rsvp_guests where party_id = new.party_id
    ) > 12 then
        raise exception 'A party cannot have more than 12 guests';
    end if;
    return new;
end;
$$;

drop trigger if exists trg_enforce_rsvp_party_guest_limit on public.rsvp_guests;
create trigger trg_enforce_rsvp_party_guest_limit
after insert or update on public.rsvp_guests
for each row
execute function public.enforce_rsvp_party_guest_limit();

alter table public.rsvp_parties enable row level security;
alter table public.rsvp_guests enable row level security;

-- Public submission goes only through the submit_rsvp RPC below (security definer),
-- so no anon grants/policies are needed directly on these tables.

drop policy if exists "Admins can read RSVP parties" on public.rsvp_parties;
create policy "Admins can read RSVP parties"
on public.rsvp_parties
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can insert RSVP parties" on public.rsvp_parties;
create policy "Admins can insert RSVP parties"
on public.rsvp_parties
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update RSVP parties" on public.rsvp_parties;
create policy "Admins can update RSVP parties"
on public.rsvp_parties
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete RSVP parties" on public.rsvp_parties;
create policy "Admins can delete RSVP parties"
on public.rsvp_parties
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Admins can read RSVP guests" on public.rsvp_guests;
create policy "Admins can read RSVP guests"
on public.rsvp_guests
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can insert RSVP guests" on public.rsvp_guests;
create policy "Admins can insert RSVP guests"
on public.rsvp_guests
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update RSVP guests" on public.rsvp_guests;
create policy "Admins can update RSVP guests"
on public.rsvp_guests
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete RSVP guests" on public.rsvp_guests;
create policy "Admins can delete RSVP guests"
on public.rsvp_guests
for delete
to authenticated
using (public.is_admin());

grant select, insert, update, delete on public.rsvp_parties to authenticated;
grant select, insert, update, delete on public.rsvp_guests to authenticated;
grant usage on all sequences in schema public to authenticated;

-- Atomic RPC used by the public RSVP form (anon) and by the admin "create" flow.
-- p_guests shape: [{ "first_name": text, "last_name": text, "is_child": bool,
--                     "age": int|null, "allergies": text|null, "is_primary_contact": bool }, ...]
create or replace function public.submit_rsvp(p_notes text, p_guests jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    v_party_id integer;
    v_guest_count integer;
    v_primary_count integer;
begin
    select count(*) into v_guest_count from jsonb_array_elements(p_guests);

    if v_guest_count < 1 or v_guest_count > 12 then
        raise exception 'A party must have between 1 and 12 guests';
    end if;

    select count(*) into v_primary_count
    from jsonb_array_elements(p_guests) as g
    where (g->>'is_primary_contact')::boolean;

    if v_primary_count <> 1 then
        raise exception 'Exactly one guest must be the primary contact';
    end if;

    insert into public.rsvp_parties (notes)
    values (nullif(btrim(coalesce(p_notes, '')), ''))
    returning id into v_party_id;

    insert into public.rsvp_guests (
        party_id, first_name, last_name, is_child, age, allergies,
        is_primary_contact, guest_order
    )
    select
        v_party_id,
        g->>'first_name',
        g->>'last_name',
        coalesce((g->>'is_child')::boolean, false),
        nullif(g->>'age', '')::smallint,
        nullif(btrim(coalesce(g->>'allergies', '')), ''),
        coalesce((g->>'is_primary_contact')::boolean, false),
        (row_number() over () - 1)::smallint
    from jsonb_array_elements(p_guests) as g;

    return v_party_id;
end;
$$;

grant execute on function public.submit_rsvp(text, jsonb) to anon, authenticated;

-- Atomic RPC used by the admin panel to edit an existing party: replaces its
-- entire guest list (delete + reinsert) so partial/inconsistent updates can't happen.
create or replace function public.admin_update_rsvp_party(
    p_party_id integer, p_notes text, p_guests jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_guest_count integer;
    v_primary_count integer;
begin
    if not public.is_admin() then
        raise exception 'Only admins can update RSVP parties';
    end if;

    select count(*) into v_guest_count from jsonb_array_elements(p_guests);

    if v_guest_count < 1 or v_guest_count > 12 then
        raise exception 'A party must have between 1 and 12 guests';
    end if;

    select count(*) into v_primary_count
    from jsonb_array_elements(p_guests) as g
    where (g->>'is_primary_contact')::boolean;

    if v_primary_count <> 1 then
        raise exception 'Exactly one guest must be the primary contact';
    end if;

    update public.rsvp_parties
    set notes = nullif(btrim(coalesce(p_notes, '')), '')
    where id = p_party_id;

    delete from public.rsvp_guests where party_id = p_party_id;

    insert into public.rsvp_guests (
        party_id, first_name, last_name, is_child, age, allergies,
        is_primary_contact, guest_order
    )
    select
        p_party_id,
        g->>'first_name',
        g->>'last_name',
        coalesce((g->>'is_child')::boolean, false),
        nullif(g->>'age', '')::smallint,
        nullif(btrim(coalesce(g->>'allergies', '')), ''),
        coalesce((g->>'is_primary_contact')::boolean, false),
        (row_number() over () - 1)::smallint
    from jsonb_array_elements(p_guests) as g;
end;
$$;

grant execute on function public.admin_update_rsvp_party(integer, text, jsonb) to authenticated;
